[package]
name = "dbtranslate_derive"
description = "proc macro for dbtranslate"
version = "0.1.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
