[package]
name = "dbtranslate_two"
description = "A sqlparser for dbt based on sqlglot."
version = "0.1.0"
edition = "2021"

[lib]
name = "dbtranslate_two"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.95"